/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-bQ7eEQkuz05vIUqCXWCqAwdhs60GR1h1uSJwdtYyLzpRJx7WDqea57fJFMEUYWg6JIWZpuG5NMKEMq9P0ePKrux7gXu62Mm1AFk2oytFCvZgmsaz20hBq-VV",
  "tt": "tt-1-kmjy6esxG7c5AIcfWVpegl7QXYgHQQtXhcw1Ljb-HrE=",
  "version": "2020-11-20"
}

export default ebconfig;